### ISSUE TITLE
Processing state incorrect

### ISSUE THREAD

**Issue by outsider787** [outsider787/construkted_reality#127]
After processing is complete, the tasks are still showing in "Tasks being processed"

Probably related to issue #126  ????

![image](https://user-images.githubusercontent.com/13057505/87939384-ff2f0280-ca65-11ea-825f-8a4d9985b1db.png)

**Comment by 3DGISKing** [comment]
“Tasks being processed” list includes tasks which are not completed and are still running.
You can check the status of each task.
![image](https://user-images.githubusercontent.com/26606704/87974514-c2fab100-cafc-11ea-927f-83182dd583d4.png)
Status 20  means "RUNNING".

It was defined in the API as follows.
![image](https://user-images.githubusercontent.com/26606704/87974683-07864c80-cafd-11ea-8026-b9f64af34528.png)
