### ISSUE TITLE
Reverted from backup, but API not working

### ISSUE THREAD

**Issue by outsider787** [outsider787/construkted_reality#128]
I reverted the production server from backup.
The settings tell me that the API server is live, but when I try to upload an asset I get a message "Can not find any api url"

![image](https://user-images.githubusercontent.com/13057505/87980022-f60f5700-caa0-11ea-8dd0-491f0eb87da2.png)

![image](https://user-images.githubusercontent.com/13057505/87979969-e132c380-caa0-11ea-858e-1e4d55578a1f.png)

**Comment by 3DGISKing** [comment]
Let me check.

**Comment by 3DGISKing** [comment]
I could not see the same thinng on my side.
![image](https://user-images.githubusercontent.com/26606704/88002304-cc077480-cb34-11ea-951c-751830589fa0.png)

**Comment by 3DGISKing** [comment]
It looks like that current state is some bit complex.
tile01.construkted.com, tile.api.construkted, tile-gw3.construkted.com have the same ip and moreover some of them look to have same port for API.
And construked.com was not updated with the latest source.
Also FTP to tile01.construkted.com does not work.
I will discuss and work when you are online.

**Comment by outsider787** [comment]
Only tile.api.construkted, tile-gw3.construkted.com should h ave the same IP.
tile01.construkted.com doesn't exist anymore (it had an IP of 3.21.66.209)

**Comment by outsider787** [comment]
The nodeJS seems to be running on tile.api.construkted.com
![image](https://user-images.githubusercontent.com/13057505/88042085-5f32b100-cb19-11ea-9ab9-a617ee51ef0d.png)
