### ISSUE TITLE
Error shown for old assets

### ISSUE THREAD

**Issue by outsider787** [outsider787/construkted_reality#130]
On the User Profile-> Assets page (https://construkted.com/profile/?active_tab=posts) old assets show ERROR.

1. Uploaded file shows "Completed" which is correct
2. All other old posts show "ERROR"

![image](https://user-images.githubusercontent.com/13057505/88196166-e281fe80-cc0e-11ea-9002-dfce2fc8d6bd.png)

**Comment by 3DGISKing** [comment]
Let me fix.

**Comment by 3DGISKing** [comment]
fixed

**Comment by outsider787** [comment]
What was the problem?
