### ISSUE TITLE
File : control_asset_details.php is strange.

### ISSUE THREAD

**Issue by 3DGISKing** [outsider787/construkted_reality#131]
Whenever we change /wp-content/themes/gowatch-child/control_asset_details.php, we faces on 404 error unless we change the permission of the file.

**Comment by outsider787** [comment]
I guess that the file permissions don't get stored on github?
I will speak with Stefan about this.

**Comment by 3DGISKing** [comment]
I already tried to save the file permission to github.
But when I changed the file permission and trid to push it, I got the following message : "nothing to change"

**Comment by outsider787** [comment]
permissions on that file need to be 644, otherwise we get 404 error
