### ISSUE TITLE
FPV mode doesn't work if model is not Geo-referenced

### ISSUE THREAD

**Issue by outsider787** [outsider787/construkted_reality#135]
- When an asset is NOT geo-referenced, can't enter  FPV mode.
- If asset is geo-referenced, then FPV mode works.

![image](https://user-images.githubusercontent.com/13057505/88466178-b927d380-ce97-11ea-9422-b41ba071caf1.png)

**Comment by 3DGISKing** [comment]
Entering FPV mode does not always fail for all asset.
For example we can enter FPV mode for this asst.
https://construkted.com/asset/aja74av1h82/
 
I think the entering FPV fails because user double click at outside of the 3dtileset.
If it is right, do you want entering FPV even in such cases?

**Comment by outsider787** [comment]
FPV should NOT be possible if user clicks outside tileset. 

I cannot enter FPV mode on the asset you listed ( https://construkted.com/asset/aja74av1h82/)

![asset-no-FPV-2](https://user-images.githubusercontent.com/13057505/89744621-c7234a00-da7c-11ea-9e79-13f1215c4a16.gif)

**Comment by 3DGISKing** [comment]
![5bBqc2OcYF](https://user-images.githubusercontent.com/26606704/89784480-539c3e00-db4b-11ea-9033-7599c22ffcca.gif)

**Comment by 3DGISKing** [comment]
Please check.
When the globe is not shown(or asset is not georeferenced), globe.getHeight will always fail.
So we will check only the scene.pickFromRay 's result for checking if user click the inside of tileset.
